# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
dist: xenial
if: branch = master OR tag IS present OR type = pull_request
julia:
  - 1
notifications:
  email: false
before_script:
  - git config --global url.git@github.com:.insteadOf https://github.com/
  - julia --color=yes --project= -e 'using Pkg; Pkg.update()'  # Install General
  - git clone git@github.com:beacon-biosignals/BeaconRegistry.git ~/.julia/registries/Beacon
codecov: true
