name: doctests
on:
  push:
    branches:
      - 'main'
      - /^release-.*$/
    tags: '*'
  pull_request:
jobs:
  doctests:
    name: Doctests (Julia ${{ matrix.version }} - ${{ github.event_name }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        julia-version: [1.6.1]
    steps:
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}
      - uses: actions/checkout@v1
      - name: Instantiate `docs` environment and run
        run: |
          julia  --project=docs -e 'using Pkg; Pkg.instantiate()'
          julia  --project=docs 'docs/fix_doctests.jl'
      - uses: reviewdog/action-suggester@v1
        if: github.event_name == 'pull_request'
        with:
          tool_name: Documenter (doctests)
          fail_on_error: true
